// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthRegistBuf.proto

package protobuf;

public final class AuthRegistBuf {
  private AuthRegistBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AuthRegistVoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string mobile = 1;
    /**
     * <code>required string mobile = 1;</code>
     */
    boolean hasMobile();
    /**
     * <code>required string mobile = 1;</code>
     */
    java.lang.String getMobile();
    /**
     * <code>required string mobile = 1;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    // required string password = 2;
    /**
     * <code>required string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // required string validCode = 3;
    /**
     * <code>required string validCode = 3;</code>
     */
    boolean hasValidCode();
    /**
     * <code>required string validCode = 3;</code>
     */
    java.lang.String getValidCode();
    /**
     * <code>required string validCode = 3;</code>
     */
    com.google.protobuf.ByteString
        getValidCodeBytes();

    // required string hiName = 4;
    /**
     * <code>required string hiName = 4;</code>
     */
    boolean hasHiName();
    /**
     * <code>required string hiName = 4;</code>
     */
    java.lang.String getHiName();
    /**
     * <code>required string hiName = 4;</code>
     */
    com.google.protobuf.ByteString
        getHiNameBytes();

    // optional string uuid = 5;
    /**
     * <code>optional string uuid = 5;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 5;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 5;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    // optional double lon = 6;
    /**
     * <code>optional double lon = 6;</code>
     */
    boolean hasLon();
    /**
     * <code>optional double lon = 6;</code>
     */
    double getLon();

    // optional double lat = 7;
    /**
     * <code>optional double lat = 7;</code>
     */
    boolean hasLat();
    /**
     * <code>optional double lat = 7;</code>
     */
    double getLat();

    // optional string avatar = 8;
    /**
     * <code>optional string avatar = 8;</code>
     */
    boolean hasAvatar();
    /**
     * <code>optional string avatar = 8;</code>
     */
    java.lang.String getAvatar();
    /**
     * <code>optional string avatar = 8;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    // optional string token_id = 9;
    /**
     * <code>optional string token_id = 9;</code>
     */
    boolean hasTokenId();
    /**
     * <code>optional string token_id = 9;</code>
     */
    java.lang.String getTokenId();
    /**
     * <code>optional string token_id = 9;</code>
     */
    com.google.protobuf.ByteString
        getTokenIdBytes();
  }
  /**
   * Protobuf type {@code AuthRegistVo}
   */
  public static final class AuthRegistVo extends
      com.google.protobuf.GeneratedMessage
      implements AuthRegistVoOrBuilder {
    // Use AuthRegistVo.newBuilder() to construct.
    private AuthRegistVo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AuthRegistVo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AuthRegistVo defaultInstance;
    public static AuthRegistVo getDefaultInstance() {
      return defaultInstance;
    }

    public AuthRegistVo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AuthRegistVo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              mobile_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              validCode_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              hiName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              uuid_ = input.readBytes();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              lon_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              lat_ = input.readDouble();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              avatar_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              tokenId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.AuthRegistBuf.internal_static_AuthRegistVo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.AuthRegistBuf.internal_static_AuthRegistVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.AuthRegistBuf.AuthRegistVo.class, protobuf.AuthRegistBuf.AuthRegistVo.Builder.class);
    }

    public static com.google.protobuf.Parser<AuthRegistVo> PARSER =
        new com.google.protobuf.AbstractParser<AuthRegistVo>() {
      public AuthRegistVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthRegistVo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AuthRegistVo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string mobile = 1;
    public static final int MOBILE_FIELD_NUMBER = 1;
    private java.lang.Object mobile_;
    /**
     * <code>required string mobile = 1;</code>
     */
    public boolean hasMobile() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string mobile = 1;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mobile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mobile = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string validCode = 3;
    public static final int VALIDCODE_FIELD_NUMBER = 3;
    private java.lang.Object validCode_;
    /**
     * <code>required string validCode = 3;</code>
     */
    public boolean hasValidCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string validCode = 3;</code>
     */
    public java.lang.String getValidCode() {
      java.lang.Object ref = validCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          validCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string validCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValidCodeBytes() {
      java.lang.Object ref = validCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        validCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string hiName = 4;
    public static final int HINAME_FIELD_NUMBER = 4;
    private java.lang.Object hiName_;
    /**
     * <code>required string hiName = 4;</code>
     */
    public boolean hasHiName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string hiName = 4;</code>
     */
    public java.lang.String getHiName() {
      java.lang.Object ref = hiName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hiName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hiName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHiNameBytes() {
      java.lang.Object ref = hiName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hiName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string uuid = 5;
    public static final int UUID_FIELD_NUMBER = 5;
    private java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 5;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string uuid = 5;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double lon = 6;
    public static final int LON_FIELD_NUMBER = 6;
    private double lon_;
    /**
     * <code>optional double lon = 6;</code>
     */
    public boolean hasLon() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double lon = 6;</code>
     */
    public double getLon() {
      return lon_;
    }

    // optional double lat = 7;
    public static final int LAT_FIELD_NUMBER = 7;
    private double lat_;
    /**
     * <code>optional double lat = 7;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double lat = 7;</code>
     */
    public double getLat() {
      return lat_;
    }

    // optional string avatar = 8;
    public static final int AVATAR_FIELD_NUMBER = 8;
    private java.lang.Object avatar_;
    /**
     * <code>optional string avatar = 8;</code>
     */
    public boolean hasAvatar() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string avatar = 8;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          avatar_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string avatar = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string token_id = 9;
    public static final int TOKEN_ID_FIELD_NUMBER = 9;
    private java.lang.Object tokenId_;
    /**
     * <code>optional string token_id = 9;</code>
     */
    public boolean hasTokenId() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string token_id = 9;</code>
     */
    public java.lang.String getTokenId() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tokenId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token_id = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTokenIdBytes() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      mobile_ = "";
      password_ = "";
      validCode_ = "";
      hiName_ = "";
      uuid_ = "";
      lon_ = 0D;
      lat_ = 0D;
      avatar_ = "";
      tokenId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMobile()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValidCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHiName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMobileBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getValidCodeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getHiNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUuidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, lon_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, lat_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getAvatarBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getTokenIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMobileBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getValidCodeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getHiNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUuidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, lon_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, lat_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getAvatarBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getTokenIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.AuthRegistBuf.AuthRegistVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.AuthRegistBuf.AuthRegistVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.AuthRegistBuf.AuthRegistVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.AuthRegistBuf.AuthRegistVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.AuthRegistBuf.AuthRegistVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.AuthRegistBuf.AuthRegistVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.AuthRegistBuf.AuthRegistVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.AuthRegistBuf.AuthRegistVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.AuthRegistBuf.AuthRegistVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.AuthRegistBuf.AuthRegistVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.AuthRegistBuf.AuthRegistVo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AuthRegistVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.AuthRegistBuf.AuthRegistVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.AuthRegistBuf.internal_static_AuthRegistVo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.AuthRegistBuf.internal_static_AuthRegistVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.AuthRegistBuf.AuthRegistVo.class, protobuf.AuthRegistBuf.AuthRegistVo.Builder.class);
      }

      // Construct using protobuf.AuthRegistBuf.AuthRegistVo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mobile_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        validCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        hiName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        lon_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        avatar_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        tokenId_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.AuthRegistBuf.internal_static_AuthRegistVo_descriptor;
      }

      public protobuf.AuthRegistBuf.AuthRegistVo getDefaultInstanceForType() {
        return protobuf.AuthRegistBuf.AuthRegistVo.getDefaultInstance();
      }

      public protobuf.AuthRegistBuf.AuthRegistVo build() {
        protobuf.AuthRegistBuf.AuthRegistVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.AuthRegistBuf.AuthRegistVo buildPartial() {
        protobuf.AuthRegistBuf.AuthRegistVo result = new protobuf.AuthRegistBuf.AuthRegistVo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mobile_ = mobile_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.validCode_ = validCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hiName_ = hiName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.lon_ = lon_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.avatar_ = avatar_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.tokenId_ = tokenId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.AuthRegistBuf.AuthRegistVo) {
          return mergeFrom((protobuf.AuthRegistBuf.AuthRegistVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.AuthRegistBuf.AuthRegistVo other) {
        if (other == protobuf.AuthRegistBuf.AuthRegistVo.getDefaultInstance()) return this;
        if (other.hasMobile()) {
          bitField0_ |= 0x00000001;
          mobile_ = other.mobile_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasValidCode()) {
          bitField0_ |= 0x00000004;
          validCode_ = other.validCode_;
          onChanged();
        }
        if (other.hasHiName()) {
          bitField0_ |= 0x00000008;
          hiName_ = other.hiName_;
          onChanged();
        }
        if (other.hasUuid()) {
          bitField0_ |= 0x00000010;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasAvatar()) {
          bitField0_ |= 0x00000080;
          avatar_ = other.avatar_;
          onChanged();
        }
        if (other.hasTokenId()) {
          bitField0_ |= 0x00000100;
          tokenId_ = other.tokenId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMobile()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (!hasValidCode()) {
          
          return false;
        }
        if (!hasHiName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.AuthRegistBuf.AuthRegistVo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.AuthRegistBuf.AuthRegistVo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string mobile = 1;
      private java.lang.Object mobile_ = "";
      /**
       * <code>required string mobile = 1;</code>
       */
      public boolean hasMobile() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string mobile = 1;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mobile = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mobile = 1;</code>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mobile = 1;</code>
       */
      public Builder clearMobile() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>required string mobile = 1;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mobile_ = value;
        onChanged();
        return this;
      }

      // required string password = 2;
      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // required string validCode = 3;
      private java.lang.Object validCode_ = "";
      /**
       * <code>required string validCode = 3;</code>
       */
      public boolean hasValidCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string validCode = 3;</code>
       */
      public java.lang.String getValidCode() {
        java.lang.Object ref = validCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          validCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string validCode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValidCodeBytes() {
        java.lang.Object ref = validCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          validCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string validCode = 3;</code>
       */
      public Builder setValidCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        validCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string validCode = 3;</code>
       */
      public Builder clearValidCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        validCode_ = getDefaultInstance().getValidCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string validCode = 3;</code>
       */
      public Builder setValidCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        validCode_ = value;
        onChanged();
        return this;
      }

      // required string hiName = 4;
      private java.lang.Object hiName_ = "";
      /**
       * <code>required string hiName = 4;</code>
       */
      public boolean hasHiName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string hiName = 4;</code>
       */
      public java.lang.String getHiName() {
        java.lang.Object ref = hiName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hiName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hiName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHiNameBytes() {
        java.lang.Object ref = hiName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hiName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hiName = 4;</code>
       */
      public Builder setHiName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        hiName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hiName = 4;</code>
       */
      public Builder clearHiName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hiName_ = getDefaultInstance().getHiName();
        onChanged();
        return this;
      }
      /**
       * <code>required string hiName = 4;</code>
       */
      public Builder setHiNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        hiName_ = value;
        onChanged();
        return this;
      }

      // optional string uuid = 5;
      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 5;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string uuid = 5;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 5;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 5;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 5;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uuid_ = value;
        onChanged();
        return this;
      }

      // optional double lon = 6;
      private double lon_ ;
      /**
       * <code>optional double lon = 6;</code>
       */
      public boolean hasLon() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double lon = 6;</code>
       */
      public double getLon() {
        return lon_;
      }
      /**
       * <code>optional double lon = 6;</code>
       */
      public Builder setLon(double value) {
        bitField0_ |= 0x00000020;
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double lon = 6;</code>
       */
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000020);
        lon_ = 0D;
        onChanged();
        return this;
      }

      // optional double lat = 7;
      private double lat_ ;
      /**
       * <code>optional double lat = 7;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double lat = 7;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>optional double lat = 7;</code>
       */
      public Builder setLat(double value) {
        bitField0_ |= 0x00000040;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double lat = 7;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000040);
        lat_ = 0D;
        onChanged();
        return this;
      }

      // optional string avatar = 8;
      private java.lang.Object avatar_ = "";
      /**
       * <code>optional string avatar = 8;</code>
       */
      public boolean hasAvatar() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string avatar = 8;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string avatar = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string avatar = 8;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string avatar = 8;</code>
       */
      public Builder clearAvatar() {
        bitField0_ = (bitField0_ & ~0x00000080);
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>optional string avatar = 8;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        avatar_ = value;
        onChanged();
        return this;
      }

      // optional string token_id = 9;
      private java.lang.Object tokenId_ = "";
      /**
       * <code>optional string token_id = 9;</code>
       */
      public boolean hasTokenId() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string token_id = 9;</code>
       */
      public java.lang.String getTokenId() {
        java.lang.Object ref = tokenId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tokenId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token_id = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTokenIdBytes() {
        java.lang.Object ref = tokenId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token_id = 9;</code>
       */
      public Builder setTokenId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        tokenId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token_id = 9;</code>
       */
      public Builder clearTokenId() {
        bitField0_ = (bitField0_ & ~0x00000100);
        tokenId_ = getDefaultInstance().getTokenId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token_id = 9;</code>
       */
      public Builder setTokenIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        tokenId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AuthRegistVo)
    }

    static {
      defaultInstance = new AuthRegistVo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AuthRegistVo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthRegistVo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AuthRegistVo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023AuthRegistBuf.proto\"\235\001\n\014AuthRegistVo\022\016" +
      "\n\006mobile\030\001 \002(\t\022\020\n\010password\030\002 \002(\t\022\021\n\tvali" +
      "dCode\030\003 \002(\t\022\016\n\006hiName\030\004 \002(\t\022\014\n\004uuid\030\005 \001(" +
      "\t\022\013\n\003lon\030\006 \001(\001\022\013\n\003lat\030\007 \001(\001\022\016\n\006avatar\030\010 " +
      "\001(\t\022\020\n\010token_id\030\t \001(\tB\"\n\021protob" +
      "ufB\rAuthRegistBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_AuthRegistVo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_AuthRegistVo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AuthRegistVo_descriptor,
              new java.lang.String[] { "Mobile", "Password", "ValidCode", "HiName", "Uuid", "Lon", "Lat", "Avatar", "TokenId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
