// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameInitBuf.proto

package protobuf;

public final class GameInitBuf {
  private GameInitBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameInitVoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 player_id = 1;
    /**
     * <code>required int64 player_id = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int64 player_id = 1;</code>
     */
    long getPlayerId();

    // required int32 game_type = 2;
    /**
     * <code>required int32 game_type = 2;</code>
     */
    boolean hasGameType();
    /**
     * <code>required int32 game_type = 2;</code>
     */
    int getGameType();

    // optional int64 self_player_id = 3;
    /**
     * <code>optional int64 self_player_id = 3;</code>
     */
    boolean hasSelfPlayerId();
    /**
     * <code>optional int64 self_player_id = 3;</code>
     */
    long getSelfPlayerId();

    // required int32 level = 4;
    /**
     * <code>required int32 level = 4;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 4;</code>
     */
    int getLevel();

    // optional string spare1 = 5;
    /**
     * <code>optional string spare1 = 5;</code>
     */
    boolean hasSpare1();
    /**
     * <code>optional string spare1 = 5;</code>
     */
    java.lang.String getSpare1();
    /**
     * <code>optional string spare1 = 5;</code>
     */
    com.google.protobuf.ByteString
        getSpare1Bytes();

    // optional string spare2 = 6;
    /**
     * <code>optional string spare2 = 6;</code>
     */
    boolean hasSpare2();
    /**
     * <code>optional string spare2 = 6;</code>
     */
    java.lang.String getSpare2();
    /**
     * <code>optional string spare2 = 6;</code>
     */
    com.google.protobuf.ByteString
        getSpare2Bytes();

    // optional string spare3 = 7;
    /**
     * <code>optional string spare3 = 7;</code>
     */
    boolean hasSpare3();
    /**
     * <code>optional string spare3 = 7;</code>
     */
    java.lang.String getSpare3();
    /**
     * <code>optional string spare3 = 7;</code>
     */
    com.google.protobuf.ByteString
        getSpare3Bytes();

    // optional string spare4 = 8;
    /**
     * <code>optional string spare4 = 8;</code>
     */
    boolean hasSpare4();
    /**
     * <code>optional string spare4 = 8;</code>
     */
    java.lang.String getSpare4();
    /**
     * <code>optional string spare4 = 8;</code>
     */
    com.google.protobuf.ByteString
        getSpare4Bytes();

    // optional string spare5 = 9;
    /**
     * <code>optional string spare5 = 9;</code>
     */
    boolean hasSpare5();
    /**
     * <code>optional string spare5 = 9;</code>
     */
    java.lang.String getSpare5();
    /**
     * <code>optional string spare5 = 9;</code>
     */
    com.google.protobuf.ByteString
        getSpare5Bytes();
  }
  /**
   * Protobuf type {@code GameInitVo}
   */
  public static final class GameInitVo extends
      com.google.protobuf.GeneratedMessage
      implements GameInitVoOrBuilder {
    // Use GameInitVo.newBuilder() to construct.
    private GameInitVo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameInitVo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameInitVo defaultInstance;
    public static GameInitVo getDefaultInstance() {
      return defaultInstance;
    }

    public GameInitVo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameInitVo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gameType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              selfPlayerId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              level_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              spare1_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              spare2_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              spare3_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              spare4_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              spare5_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.GameInitBuf.internal_static_GameInitVo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.GameInitBuf.internal_static_GameInitVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.GameInitBuf.GameInitVo.class, protobuf.GameInitBuf.GameInitVo.Builder.class);
    }

    public static com.google.protobuf.Parser<GameInitVo> PARSER =
        new com.google.protobuf.AbstractParser<GameInitVo>() {
      public GameInitVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameInitVo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameInitVo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 player_id = 1;
    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>required int64 player_id = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 player_id = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    // required int32 game_type = 2;
    public static final int GAME_TYPE_FIELD_NUMBER = 2;
    private int gameType_;
    /**
     * <code>required int32 game_type = 2;</code>
     */
    public boolean hasGameType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 game_type = 2;</code>
     */
    public int getGameType() {
      return gameType_;
    }

    // optional int64 self_player_id = 3;
    public static final int SELF_PLAYER_ID_FIELD_NUMBER = 3;
    private long selfPlayerId_;
    /**
     * <code>optional int64 self_player_id = 3;</code>
     */
    public boolean hasSelfPlayerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 self_player_id = 3;</code>
     */
    public long getSelfPlayerId() {
      return selfPlayerId_;
    }

    // required int32 level = 4;
    public static final int LEVEL_FIELD_NUMBER = 4;
    private int level_;
    /**
     * <code>required int32 level = 4;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 level = 4;</code>
     */
    public int getLevel() {
      return level_;
    }

    // optional string spare1 = 5;
    public static final int SPARE1_FIELD_NUMBER = 5;
    private java.lang.Object spare1_;
    /**
     * <code>optional string spare1 = 5;</code>
     */
    public boolean hasSpare1() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string spare1 = 5;</code>
     */
    public java.lang.String getSpare1() {
      java.lang.Object ref = spare1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          spare1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string spare1 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSpare1Bytes() {
      java.lang.Object ref = spare1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        spare1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string spare2 = 6;
    public static final int SPARE2_FIELD_NUMBER = 6;
    private java.lang.Object spare2_;
    /**
     * <code>optional string spare2 = 6;</code>
     */
    public boolean hasSpare2() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string spare2 = 6;</code>
     */
    public java.lang.String getSpare2() {
      java.lang.Object ref = spare2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          spare2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string spare2 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSpare2Bytes() {
      java.lang.Object ref = spare2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        spare2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string spare3 = 7;
    public static final int SPARE3_FIELD_NUMBER = 7;
    private java.lang.Object spare3_;
    /**
     * <code>optional string spare3 = 7;</code>
     */
    public boolean hasSpare3() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string spare3 = 7;</code>
     */
    public java.lang.String getSpare3() {
      java.lang.Object ref = spare3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          spare3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string spare3 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSpare3Bytes() {
      java.lang.Object ref = spare3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        spare3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string spare4 = 8;
    public static final int SPARE4_FIELD_NUMBER = 8;
    private java.lang.Object spare4_;
    /**
     * <code>optional string spare4 = 8;</code>
     */
    public boolean hasSpare4() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string spare4 = 8;</code>
     */
    public java.lang.String getSpare4() {
      java.lang.Object ref = spare4_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          spare4_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string spare4 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSpare4Bytes() {
      java.lang.Object ref = spare4_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        spare4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string spare5 = 9;
    public static final int SPARE5_FIELD_NUMBER = 9;
    private java.lang.Object spare5_;
    /**
     * <code>optional string spare5 = 9;</code>
     */
    public boolean hasSpare5() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string spare5 = 9;</code>
     */
    public java.lang.String getSpare5() {
      java.lang.Object ref = spare5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          spare5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string spare5 = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSpare5Bytes() {
      java.lang.Object ref = spare5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        spare5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      playerId_ = 0L;
      gameType_ = 0;
      selfPlayerId_ = 0L;
      level_ = 0;
      spare1_ = "";
      spare2_ = "";
      spare3_ = "";
      spare4_ = "";
      spare5_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGameType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, gameType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, selfPlayerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSpare1Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSpare2Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSpare3Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getSpare4Bytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getSpare5Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gameType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, selfPlayerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSpare1Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSpare2Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSpare3Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getSpare4Bytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getSpare5Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.GameInitBuf.GameInitVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.GameInitBuf.GameInitVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.GameInitBuf.GameInitVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.GameInitBuf.GameInitVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.GameInitBuf.GameInitVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.GameInitBuf.GameInitVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.GameInitBuf.GameInitVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.GameInitBuf.GameInitVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.GameInitBuf.GameInitVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.GameInitBuf.GameInitVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.GameInitBuf.GameInitVo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameInitVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.GameInitBuf.GameInitVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.GameInitBuf.internal_static_GameInitVo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.GameInitBuf.internal_static_GameInitVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.GameInitBuf.GameInitVo.class, protobuf.GameInitBuf.GameInitVo.Builder.class);
      }

      // Construct using protobuf.GameInitBuf.GameInitVo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        gameType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        selfPlayerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        spare1_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        spare2_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        spare3_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        spare4_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        spare5_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.GameInitBuf.internal_static_GameInitVo_descriptor;
      }

      public protobuf.GameInitBuf.GameInitVo getDefaultInstanceForType() {
        return protobuf.GameInitBuf.GameInitVo.getDefaultInstance();
      }

      public protobuf.GameInitBuf.GameInitVo build() {
        protobuf.GameInitBuf.GameInitVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.GameInitBuf.GameInitVo buildPartial() {
        protobuf.GameInitBuf.GameInitVo result = new protobuf.GameInitBuf.GameInitVo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gameType_ = gameType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.selfPlayerId_ = selfPlayerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.spare1_ = spare1_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.spare2_ = spare2_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.spare3_ = spare3_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.spare4_ = spare4_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.spare5_ = spare5_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.GameInitBuf.GameInitVo) {
          return mergeFrom((protobuf.GameInitBuf.GameInitVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.GameInitBuf.GameInitVo other) {
        if (other == protobuf.GameInitBuf.GameInitVo.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasGameType()) {
          setGameType(other.getGameType());
        }
        if (other.hasSelfPlayerId()) {
          setSelfPlayerId(other.getSelfPlayerId());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasSpare1()) {
          bitField0_ |= 0x00000010;
          spare1_ = other.spare1_;
          onChanged();
        }
        if (other.hasSpare2()) {
          bitField0_ |= 0x00000020;
          spare2_ = other.spare2_;
          onChanged();
        }
        if (other.hasSpare3()) {
          bitField0_ |= 0x00000040;
          spare3_ = other.spare3_;
          onChanged();
        }
        if (other.hasSpare4()) {
          bitField0_ |= 0x00000080;
          spare4_ = other.spare4_;
          onChanged();
        }
        if (other.hasSpare5()) {
          bitField0_ |= 0x00000100;
          spare5_ = other.spare5_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasGameType()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.GameInitBuf.GameInitVo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.GameInitBuf.GameInitVo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 player_id = 1;
      private long playerId_ ;
      /**
       * <code>required int64 player_id = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 player_id = 1;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int64 player_id = 1;</code>
       */
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 player_id = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 game_type = 2;
      private int gameType_ ;
      /**
       * <code>required int32 game_type = 2;</code>
       */
      public boolean hasGameType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 game_type = 2;</code>
       */
      public int getGameType() {
        return gameType_;
      }
      /**
       * <code>required int32 game_type = 2;</code>
       */
      public Builder setGameType(int value) {
        bitField0_ |= 0x00000002;
        gameType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 game_type = 2;</code>
       */
      public Builder clearGameType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gameType_ = 0;
        onChanged();
        return this;
      }

      // optional int64 self_player_id = 3;
      private long selfPlayerId_ ;
      /**
       * <code>optional int64 self_player_id = 3;</code>
       */
      public boolean hasSelfPlayerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 self_player_id = 3;</code>
       */
      public long getSelfPlayerId() {
        return selfPlayerId_;
      }
      /**
       * <code>optional int64 self_player_id = 3;</code>
       */
      public Builder setSelfPlayerId(long value) {
        bitField0_ |= 0x00000004;
        selfPlayerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 self_player_id = 3;</code>
       */
      public Builder clearSelfPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        selfPlayerId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 level = 4;
      private int level_ ;
      /**
       * <code>required int32 level = 4;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 level = 4;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 4;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000008;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 4;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        onChanged();
        return this;
      }

      // optional string spare1 = 5;
      private java.lang.Object spare1_ = "";
      /**
       * <code>optional string spare1 = 5;</code>
       */
      public boolean hasSpare1() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string spare1 = 5;</code>
       */
      public java.lang.String getSpare1() {
        java.lang.Object ref = spare1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          spare1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string spare1 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSpare1Bytes() {
        java.lang.Object ref = spare1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          spare1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string spare1 = 5;</code>
       */
      public Builder setSpare1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        spare1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare1 = 5;</code>
       */
      public Builder clearSpare1() {
        bitField0_ = (bitField0_ & ~0x00000010);
        spare1_ = getDefaultInstance().getSpare1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare1 = 5;</code>
       */
      public Builder setSpare1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        spare1_ = value;
        onChanged();
        return this;
      }

      // optional string spare2 = 6;
      private java.lang.Object spare2_ = "";
      /**
       * <code>optional string spare2 = 6;</code>
       */
      public boolean hasSpare2() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string spare2 = 6;</code>
       */
      public java.lang.String getSpare2() {
        java.lang.Object ref = spare2_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          spare2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string spare2 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSpare2Bytes() {
        java.lang.Object ref = spare2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          spare2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string spare2 = 6;</code>
       */
      public Builder setSpare2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        spare2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare2 = 6;</code>
       */
      public Builder clearSpare2() {
        bitField0_ = (bitField0_ & ~0x00000020);
        spare2_ = getDefaultInstance().getSpare2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare2 = 6;</code>
       */
      public Builder setSpare2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        spare2_ = value;
        onChanged();
        return this;
      }

      // optional string spare3 = 7;
      private java.lang.Object spare3_ = "";
      /**
       * <code>optional string spare3 = 7;</code>
       */
      public boolean hasSpare3() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string spare3 = 7;</code>
       */
      public java.lang.String getSpare3() {
        java.lang.Object ref = spare3_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          spare3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string spare3 = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSpare3Bytes() {
        java.lang.Object ref = spare3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          spare3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string spare3 = 7;</code>
       */
      public Builder setSpare3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        spare3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare3 = 7;</code>
       */
      public Builder clearSpare3() {
        bitField0_ = (bitField0_ & ~0x00000040);
        spare3_ = getDefaultInstance().getSpare3();
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare3 = 7;</code>
       */
      public Builder setSpare3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        spare3_ = value;
        onChanged();
        return this;
      }

      // optional string spare4 = 8;
      private java.lang.Object spare4_ = "";
      /**
       * <code>optional string spare4 = 8;</code>
       */
      public boolean hasSpare4() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string spare4 = 8;</code>
       */
      public java.lang.String getSpare4() {
        java.lang.Object ref = spare4_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          spare4_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string spare4 = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSpare4Bytes() {
        java.lang.Object ref = spare4_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          spare4_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string spare4 = 8;</code>
       */
      public Builder setSpare4(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        spare4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare4 = 8;</code>
       */
      public Builder clearSpare4() {
        bitField0_ = (bitField0_ & ~0x00000080);
        spare4_ = getDefaultInstance().getSpare4();
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare4 = 8;</code>
       */
      public Builder setSpare4Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        spare4_ = value;
        onChanged();
        return this;
      }

      // optional string spare5 = 9;
      private java.lang.Object spare5_ = "";
      /**
       * <code>optional string spare5 = 9;</code>
       */
      public boolean hasSpare5() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string spare5 = 9;</code>
       */
      public java.lang.String getSpare5() {
        java.lang.Object ref = spare5_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          spare5_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string spare5 = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSpare5Bytes() {
        java.lang.Object ref = spare5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          spare5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string spare5 = 9;</code>
       */
      public Builder setSpare5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        spare5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare5 = 9;</code>
       */
      public Builder clearSpare5() {
        bitField0_ = (bitField0_ & ~0x00000100);
        spare5_ = getDefaultInstance().getSpare5();
        onChanged();
        return this;
      }
      /**
       * <code>optional string spare5 = 9;</code>
       */
      public Builder setSpare5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        spare5_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GameInitVo)
    }

    static {
      defaultInstance = new GameInitVo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GameInitVo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GameInitVo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameInitVo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021GameInitBuf.proto\"\251\001\n\nGameInitVo\022\021\n\tpl" +
      "ayer_id\030\001 \002(\003\022\021\n\tgame_type\030\002 \002(\005\022\026\n\016self" +
      "_player_id\030\003 \001(\003\022\r\n\005level\030\004 \002(\005\022\016\n\006spare" +
      "1\030\005 \001(\t\022\016\n\006spare2\030\006 \001(\t\022\016\n\006spare3\030\007 \001(\t\022" +
      "\016\n\006spare4\030\010 \001(\t\022\016\n\006spare5\030\t \001(\tB\027\n\010proto" +
      "bufB\013GameInitBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GameInitVo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GameInitVo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GameInitVo_descriptor,
              new java.lang.String[] { "PlayerId", "GameType", "SelfPlayerId", "Level", "Spare1", "Spare2", "Spare3", "Spare4", "Spare5", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
